---
services: docker

env:
  - distro: centos7
  - distro: ubuntu1604
  - distro: debian9

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Run script to test if XHProf is available and working.
  - 'docker exec ${container_id} env TERM=xterm php /etc/ansible/roles/role_under_test/tests/xhprof-test.php'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
